In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Twitter_Full.csv')
df.head()

text  \
0  Being s mom is cleaning 24/7 the same shit ove...   
1  And now we have been given the walkthru book b...   
2  Wishing YOU Peace Joy & Love! JoyTrain MentalH...   
3   speak-no-evil monkey Can I Be Honest With You...   
4  Psy Do u hv any regrets? Me No Psy Are you hap...   

                                            hashtags  labels  
0                       ['momlife', 'kids', 'tired']       1  
1                                       ['walkthru']       0  
2  ['Peace', 'Joy', 'Love', 'JoyTrain', 'MentalHe...       0  
3  ['therapy', 'help', 'NLP', 'CBT', 'hypnotherap...       1  
4                                                 []       0

# New Section

In [ ]:
df.describe()

labels
count  8900.000000
mean      0.509438
std       0.499939
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [ ]:
df.isnull()

text  hashtags  labels
0     False     False   False
1     False     False   False
2     False     False   False
3     False     False   False
4     False     False   False
...     ...       ...     ...
8895  False     False   False
8896  False     False   False
8897  False     False   False
8898  False     False   False
8899  False     False   False

[8900 rows x 3 columns]

In [ ]:
df.isnull().sum()

text        0
hashtags    8
labels      0
dtype: int64

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
import string

In [ ]:
nltk.download('stopwords')
stemmer = nltk.SnowballStemmer('english')
stopword = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
def clean(text):
    text = str(text).lower()
    text = re.sub('\[.*?\]',' ',text)
    text = re.sub('https?://\S+/www\. \S+', ' ', text)
    text = re.sub('<. *?>+', ' ', text)
    text = re.sub(' [%s]' % re.escape(string.punctuation), ' ', text)
    text = re.sub(' \n',' ', text)
    text = re.sub(' \w*\d\w*' ,' ', text)
    text = [word for word in text.split(' ') if word not in stopword]
    text =" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ') ]
    text = " ".join(text)
    return text
df["text"] = df["text"].apply(clean)

In [ ]:
from sklearn. feature_extraction. text import CountVectorizer
from sklearn. model_selection import train_test_split

In [ ]:
from sklearn. feature_extraction. text import CountVectorizer
from sklearn. model_selection import train_test_split

x = np.array (df["text"])
y = np.array (df["labels"])

cv = CountVectorizer ()
X = cv. fit_transform(x)
print(X)
xtrain, xtest, ytrain, ytest = train_test_split(X, y,test_size=0.33)

  (0, 12405)	1
  (0, 3617)	1
  (0, 17085)	1
  (0, 6008)	1
  (0, 16021)	1
  (0, 6301)	1
  (0, 12075)	1
  (0, 568)	1
  (0, 12413)	1
  (0, 10405)	1
  (0, 19350)	1
  (1, 7713)	1
  (1, 20563)	1
  (1, 2379)	1
  (1, 1677)	1
  (1, 20927)	1
  (1, 16611)	1
  (1, 14203)	1
  (1, 13611)	1
  (1, 8069)	1
  (1, 6480)	1
  (1, 9644)	1
  (1, 6350)	1
  (2, 21033)	1
  (2, 14211)	1
  :	:
  (8897, 5044)	1
  (8897, 18857)	2
  (8898, 11952)	1
  (8898, 11988)	1
  (8898, 4717)	1
  (8898, 16882)	1
  (8898, 3288)	1
  (8898, 8580)	2
  (8898, 6904)	1
  (8898, 15321)	2
  (8898, 5380)	1
  (8898, 17138)	1
  (8898, 20319)	1
  (8898, 3295)	1
  (8898, 7637)	1
  (8899, 19350)	1
  (8899, 7398)	1
  (8899, 6646)	1
  (8899, 10636)	1
  (8899, 6142)	1
  (8899, 13188)	1
  (8899, 752)	1
  (8899, 6327)	1
  (8899, 1905)	1
  (8899, 7693)	1


In [ ]:
from sklearn.naive_bayes import BernoulliNB
f1=BernoulliNB()
f1.fit(xtrain,ytrain)

from sklearn.svm import SVC
f2 = SVC(kernel = 'rbf', random_state = 0)
f2.fit(xtrain, ytrain)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(xtrain, ytrain)

RandomForestClassifier()

In [ ]:
'''
user=input("Enter the text:")
data=cv.transform([user]).toarray()
output=model.predict(data)
if output==1:
  print("Yes,the person is in stress")
else:
  print("Not in stress")'''

'\nuser=input("Enter the text:")\ndata=cv.transform([user]).toarray()\noutput=model.predict(data)\nif output==1:\n  print("Yes,the person is in stress")\nelse:\n  print("Not in stress")'

In [ ]:
ypred = model.predict(xtest)
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(ytest,ypred)
print("********Random Forest************")
print(cm)
print(classification_report(ytest,ypred))

ypred = f1.predict(xtest)
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(ytest,ypred)
print("**********Naive Bayes**********")
print(cm)
print(classification_report(ytest,ypred))     

ypred = f2.predict(xtest)
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(ytest,ypred)
print("**********SVM**********")
print(cm)
print(classification_report(ytest,ypred))



********Random Forest************
[[1049  369]
 [ 139 1380]]
              precision    recall  f1-score   support

           0       0.88      0.74      0.81      1418
           1       0.79      0.91      0.84      1519

    accuracy                           0.83      2937
   macro avg       0.84      0.82      0.82      2937
weighted avg       0.83      0.83      0.83      2937

**********Naive Bayes**********
[[1055  363]
 [ 181 1338]]
              precision    recall  f1-score   support

           0       0.85      0.74      0.80      1418
           1       0.79      0.88      0.83      1519

    accuracy                           0.81      2937
   macro avg       0.82      0.81      0.81      2937
weighted avg       0.82      0.81      0.81      2937

**********SVM**********
[[1097  321]
 [ 156 1363]]
              precision    recall  f1-score   support

           0       0.88      0.77      0.82      1418
           1       0.81      0.90      0.85      1519

    accurac